ruby-exercisese-sample-app/config/routes.rb
Rails.application.routes.draw do
  resources :users 

  root "static_pages#home"

  get "signup" => 'users#new'
  
  get "home" => 'static_pages#home'

  get "help" => 'static_pages#help'

  get "contact" => 'static_pages#contact'

  get "about" => 'static_pages#about'

end

ruby-exercisese-sample-app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
	attr_accessible :name, :email, :password, :password_confirmation
	has_secure_password

	before_save { |user| user.email = email.downcase }		

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }	
	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true	
end

ruby-exercisese-sample-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby-exercisese-sample-app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

ruby-exercisese-sample-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			flash[:success] = "Welcome to the Sample App!"
			redirect_to @user
		else
			render 'new'
		end
	end
end

ruby-exercisese-sample-app/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby-exercisese-sample-app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

ruby-exercisese-sample-app/app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end	
end

ruby-exercisese-sample-app/app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
Ruby on Rails sample app by <a href="https://github.com/pvhau">pvhau</a>
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
</ul>
</nav>
</footer>

ruby-exercisese-sample-app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "sample app", home_path, id: "logo"%>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", home_path %></li>												
					<li><%= link_to "Help", help_path %></li>
					<li><%= link_to "Sign in", help_path %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

ruby-exercisese-sample-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
		<%= stylesheet_link_tag "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render "layouts/header" %>
		<div class="container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
			<%= render "layouts/footer" %>
		</div>		
	</body>
</html>

ruby-exercisese-sample-app/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-error">
		The form contains <%= pluralize(@user.errors.count, "error") %>.
	</div>
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

ruby-exercisese-sample-app/app/views/static_pages/about.html.erb
<% provide(:title, 'About Me') %>
<h1>About Me</h1>
<p>
The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
is a project to make a book and screencasts to teach web development
with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
is the sample application for the tutorial.
</p>

ruby-exercisese-sample-app/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Me') %>
<h1>Contact Me</h1>
<p>Contact me on <a href="https://github.com/pvhau">Github</a></p>

ruby-exercisese-sample-app/app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
Get help on the Ruby on Rails Tutorial at the
<a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
To get help on this sample app, see the
<a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

ruby-exercisese-sample-app/app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
<h1>Welcome to the Sample App</h1>
<h2>
This is the home page for the
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
sample application.
</h2>

<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

</div>

ruby-exercisese-sample-app/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
	<div class="span6 offset3">
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<%= f.label :password %>
		<%= f.password_field :password %>
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>
		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

ruby-exercisese-sample-app/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>